Feature/create collection extrinsic
freeverseio/pallet-livingassets-ownership pull request #4
Opened 2023-06-05 15:07 UTC by asiniscalchi

2023-06-06 10:16 UTC, magecnion requested changes

2023-06-06 10:16 UTC, magecnion commented on src/lib.rs
>  	#[pallet::generate_deposit(pub(super) fn deposit_event)]
what does "generate_deposit" stands for?

2023-06-06 14:47 UTC, asiniscalchi commented on src/lib.rs
>  	#[pallet::generate_deposit(pub(super) fn deposit_event)]
dunno ... but it seems it is the template node and there's no element called generate_deposit. Let's live it there

2023-06-14 14:15 UTC, magecnion approved these changes

2023-06-14 14:15 UTC, merged